"""Reassemble .text and compare every byte; this is assembly verification only."""
import argparse
import csv
import hashlib
import json
import re
import subprocess
from pathlib import Path

from elftools.elf.elffile import ELFFile
from analyze import ROOT, validated_elf, write_json


def run(command):
    result = subprocess.run([str(v) for v in command], cwd=ROOT, capture_output=True, text=True)
    if result.returncode:
        raise RuntimeError("Command failed: " + " ".join(str(v) for v in command)
                           + "\n" + (result.stderr + result.stdout)[-6000:])
    return result.stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binutils", type=Path, default=ROOT / "tools/vendor/binutils-v0.10")
    args = parser.parse_args()
    spec, original = validated_elf(ROOT / "orig/SLUS_216.68")
    with (ROOT / "orig/SLUS_216.68").open("rb") as stream:
        section = ELFFile(stream).get_section_by_name(".text")
        expected = section.data()
        address = section["sh_addr"]
    prefix = args.binutils / "mips-ps2-decompals-"
    def tool(name):
        p = Path(str(prefix) + name + ".exe")
        return p if p.exists() else Path(str(prefix) + name)
    source = ROOT / "build/disasm/SLUS_216_00100000.text.s"
    run([tool("as"), "-EL", "-march=r5900", "-mabi=eabi", "-G0", "-no-pad-sections",
         "-I", ROOT / "include", "-o", ROOT / "build/text.o", source])
    # Resolve only undefined assembler symbols through the disassembler context.
    symbols = {}
    for context in (ROOT / "build/context", ROOT / "build/context_unksegment"):
        with context.open(newline="", encoding="utf-8") as stream:
            for row in csv.DictReader(stream):
                if row["category"] == "symbol":
                    symbols[row["getName"]] = int(row["address"], 16)
    undefined = run([tool("nm"), "--undefined-only", ROOT / "build/text.o"])
    assignments = []
    for line in undefined.splitlines():
        name = line.split()[-1]
        if name not in symbols:
            # spimdisasm sometimes replaces a data symbol in its saved context
            # with a containing function, while emitted references retain D_.
            # Only accept the documented autogenerated address naming form.
            match = re.fullmatch(r"(?:D_|func_|T_|RO_|B_|STR_|FLT_|DBL_)([0-9A-Fa-f]{8})", name)
            if match is None:
                raise ValueError(f"No address for unresolved symbol {name}")
            symbols[name] = int(match.group(1), 16)
        assignments.append(f"{name} = 0x{symbols[name]:08X};")
    script = "\n".join(assignments) + f"\n_gp = {spec['gp']};\nSECTIONS {{ .text 0x{address:08X} : {{ *(.text) }} /DISCARD/ : {{ *(*) }} }}\n"
    (ROOT / "build/text.ld").write_text(script, encoding="utf-8")
    run([tool("ld"), "-EL", "-T", ROOT / "build/text.ld", "-o", ROOT / "build/text.elf", ROOT / "build/text.o"])
    with (ROOT / "build/text.elf").open("rb") as stream:
        actual = ELFFile(stream).get_section_by_name(".text").data()
    differences = [i for i, (a, b) in enumerate(zip(expected, actual)) if a != b]
    result = {"schema_version": 1, "kind": "assembly_roundtrip", "section": ".text",
              "expected_size": len(expected), "actual_size": len(actual),
              "expected_sha256": hashlib.sha256(expected).hexdigest(),
              "actual_sha256": hashlib.sha256(actual).hexdigest(),
              "identical": actual == expected, "different_bytes": len(differences) + abs(len(expected) - len(actual)),
              "first_different_addresses": [f"0x{address + i:08X}" for i in differences[:16]],
              "counts_as_source_decompilation": False}
    write_json(ROOT / "build/baseline.json", result)
    print(json.dumps(result, indent=2))
    if actual != expected:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
